
-- incremento para evitar constraint
SELECT SEQPARAMETLPLANUS.nextval FROM DUAL;

-- processos da previa
insert into cm.PARAMETLPLANUS (IDPARAMETL, IDMODULO, FUNCIONALIDADE, ROTINA, DIRETORIO_PROD, DIRETORIO_DEV, TEMPO_REPETE, TEMPO_ABORTA, CONEXAO_PROD, CONEXAO_DEV)
values (SEQPARAMETLPLANUS.nextval, 18,'PREVIA', 'PARAMETROS','\\RUBEO\PROJETOS\FB_PREVIA\PARAMETROS\','\\TAURI\PROJETOS\FB_PREVIA\PARAMETROS\',15000,NULL, 'RPROD_ETL_FOLHA_BENEF', 'TIBERO_ETL_FOLHA_BENEF_hom1'); 

insert into cm.PARAMETLPLANUS (IDPARAMETL, IDMODULO, FUNCIONALIDADE, ROTINA, DIRETORIO_PROD, DIRETORIO_DEV, TEMPO_REPETE, TEMPO_ABORTA, CONEXAO_PROD, CONEXAO_DEV)
values (SEQPARAMETLPLANUS.nextval, 18,'PREVIA', 'PREVIA','\\RUBEO\PROJETOS\FB_PREVIA\PREVIA\','\\TAURI\PROJETOS\FB_PREVIA\PREVIA\',15000,NULL, 'RPROD_ETL_FOLHA_BENEF', 'TIBERO_ETL_FOLHA_BENEF_hom1');  
