INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'CONEXAO_ETL',        'PARAMETLCONEXAO', '#!conexao!#', 'IDPARAMETL'   ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'MESCOBRANCA',    'ETL_FOLHA_PREVIA', '#!mescobranca!#', 'ID'    ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'DATAPAGTO',       'ETL_FOLHA_PREVIA', '#!datapgto!#', 'ID'       ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'IDLOTE_LISTA',      'ETL_FOLHA_PREVIA', '#!listalote!#', 'ID'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'IDEXECUCAO',     'ETL_FOLHA_PREVIA', '#!idexecucao!#', 'ID'     ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'ANOMESCOBRANCA', 'ETL_FOLHA_PREVIA', '#!anomescobranca!#', 'ID' ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'DTPAGTO_D1',     'ETL_FOLHA_PREVIA', '#!dtpgto-d1!#', 'ID'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'DTPAGTO_D2',     'ETL_FOLHA_PREVIA', '#!dtpgto-d2!#', 'ID'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'DTPAGTO_D3',     'ETL_FOLHA_PREVIA', '#!dtpgto-d3!#', 'ID'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'ID',     'ETL_FOLHA_PREVIA', '#!id!#', 'ID'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'IDPREVIABENEF',     'ETL_FOLHA_PREVIA', '#!idpreviabenef!#', 'ID'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'PCINT_SRV_DSV -d D_FUNCEF_DEV',     '', '#!cmdbasepagtoreinf!#', 'DEV'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'PCINT_SRV_PRD -d D_FUNCEF_PRD',     '', '#!cmdbasepagtoreinf!#', 'PRODUCAO'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'C:\CMSOLUCOES\EXECUTAVEIS\BIN\',     '', '#!cmdexecregra!#', 'PRODUCAO'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'C:\_CMSOLUCOES\EXECUTAVEIS\BIN\',     '', '#!cmdexecregra!#', 'DEV'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'SVC_REGRA_ETL',     '', '#!cmdexecregrauser!#', 'PRODUCAO'  ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'F000160',     '', '#!cmdexecregrauser!#', 'DEV'      ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM, FLGUSACRITPO, FLGAPLICACRITPO)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'fYeZPRael0p99X-KvvXBKU',     '', '#!cmdexecregraupsw!#', 'PRODUCAO', 1, 1 ) ;

INSERT INTO DEPARAEXTERNO(IDDEPARAEXTERNO, ATRIBUTO, VLRCM, TABELAORIGEM, VLREXTERNO, CAMPOFILTROORIGEM, FLGUSACRITPO, FLGAPLICACRITPO)
VALUES ( SEQDEPARAEXTERNO.NEXTVAL, 'ETL-PREVIA', 'f9MCLoL8hoIXTYxc3F7mxU',     '', '#!cmdexecregrapsw!#', 'DEV', 1, 0      ) ;
