{*******************************************************}
{                                                       }
{   FSM Library - by Fábio S Monteiro                   }
{                                                       }
{   Copyright © 1999  FSM Desenvolvimento               }
{                                                       }
{*******************************************************}


   {$DEFINE FSM3}
   {$IFNDEF VER100}
      {$DEFINE FSM4}
      {$IFNDEF VER120}
         {$DEFINE FSM5}
      {$ENDIF}
   {$ENDIF}

   {$DEFINE WWFSM}

   {$DEFINE CSFSM}

