{*******************************************************}
{                                                       }
{ CM Soluções Informática                               }
{ ** Todos os Direitos Reservados                       }
{ Analista Responsável: Raniere S. M. da Silva          }
{ Criado Em: 06/07/2005                                 }
{                                                       }
{*******************************************************}
{ MODO DE USAR:                                         }
{   Basta "definir" o padrão que está sendo usado.      }
{ EX:                                                   }
{   * Ao compilar no padrão 7.08.06, basta comentar a   }
{   linha referente ao UNDEF e descomentar a do DEFINE. }
{                                                       }
{   * Ao compilar no padrão 7.09.01, basta comentar as  }
{   linhas referentes aos UNDEFs e descomentar as dos   }
{   DEFINEs dos dois padrões anteriores.                }
{*******************************************************}

{ $UNDEF PADRAO_7_08_05}
{ $UNDEF PADRAO_7_09_00}
{ $UNDEF PADRAO_7_09_02}

{$DEFINE PADRAO_7_08_05}
{ $DEFINE PADRAO_7_08_06}
{$DEFINE PADRAO_7_09_00}
{$DEFINE PADRAO_7_09_02}
{ $DEFINE PADRAO_7_09_03}

{ $DEFINE DEPURANDO}
