<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContabPOC.Domain\ContabPOC.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- FUNCEF packages usando feed local -->
    <PackageReference Include="FUNCEF.Essenciais" />
    <PackageReference Include="FUNCEF.ORM" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
