CREATE OR REPLACE PROCEDURE    PR_EMP_REGRA_25523(IDMUTUARIO_P INT,
                                                  IDTITULAR_P  INT,
                                                  IDITEMEMPTMO_P INT,
                                                  IDTIPOCONTRATO_P INT,
                                                  IDOPERACAO_P     INT,
                                                  IDCONTRATOAQUITAR_P VARCHAR2,
                                                  SALDOEMPTMOQUITAR_P VARCHAR2,
                                                  DATACREDITO_P DATE,
                                                  DATAPRIMEIRAPARCELA_P DATE,
                                                  VALORMAXIMO_P NUMBER,
                                                  VALORMARGEM_P NUMBER,
                                                  TAXAJUROS_P   NUMBER,
                                                  NUMPARCELAS_P  INT,
                                                  VALORSOLICITADO_P NUMBER,
                                                  VALORFINANHAB_P NUMBER,
                                                  FINANCIAMENTO_P   INT,
                                                  LIQUIDOZERO_P     INT,
                                                  EXCEPCIONAL_P     INT,
                                                  IDCALCULO_P       INT,
                                                  USUARIO_P         VARCHAR2,
                                                  RESULTADO_P   OUT NUMBER,
                                                  RETORNO_P     OUT VARCHAR2) IS

BEGIN

PCK_EMP_REGRA_ITEMCONCESSAO_R.PR_REGRA_25523( IDMUTUARIO_P,
                                              IDTITULAR_P,
                                              IDITEMEMPTMO_P,
                                              IDTIPOCONTRATO_P,
                                              IDOPERACAO_P,
                                              IDCONTRATOAQUITAR_P,
                                              SALDOEMPTMOQUITAR_P,
                                              DATACREDITO_P,
                                              DATAPRIMEIRAPARCELA_P,
                                              VALORMAXIMO_P,
                                              VALORMARGEM_P,
                                              TAXAJUROS_P,
                                              NUMPARCELAS_P,
                                              VALORSOLICITADO_P,
                                              VALORFINANHAB_P,
                                              FINANCIAMENTO_P,
                                              LIQUIDOZERO_P,
                                              EXCEPCIONAL_P,
                                              IDCALCULO_P,
                                              USUARIO_P,
                                              RESULTADO_P,
                                              RETORNO_P);


END PR_EMP_REGRA_25523;