CREATE OR REPLACE PROCEDURE CM.PR_EMP_REGRA_25666( IDMUTUARIO_P         NUMBER,
                                                IDCONTRATO_P         NUMBER,
                                                IDTIPOCONTRATO_P     INT,
                                                IDOPERACAO_P         INT,
                                                IDTIPOEMPRESTIMO_P   INT,
                                                IDPLANO_P            INT,
                                                IDCONTRATOAQUITAR_P  VARCHAR2,
                                                NUMPARCELAS_P        INT,
                                                SALDODEVEDOR_P       NUMBER,
                                                TAXAJUROS_P          NUMBER,
                                                VALORMARGEM_P        NUMBER,
                                                QTDMESES_P           INT,
                                                DATACREDITO_P        DATE,
                                                VALORSOLICITADO_P    NUMBER,
                                                EXCEPCIONAL_P        INT,
                                                RESULTADO_P      OUT NUMBER,
                                                RETORNO_P        OUT VARCHAR2) IS
BEGIN

PCK_EMP_REGRA_VLMAXIMO_R.PR_REGRA_25666( IDMUTUARIO_P,
                                         NVL(IDCONTRATO_P,-1),
                                         IDTIPOCONTRATO_P,
                                         IDOPERACAO_P,
                                         IDMUTUARIO_P,
                                         IDTIPOEMPRESTIMO_P,
                                         IDPLANO_P,
                                         IDCONTRATOAQUITAR_P,
                                         NUMPARCELAS_P,
                                         SALDODEVEDOR_P,
                                         TAXAJUROS_P,
                                         VALORMARGEM_P,
                                         QTDMESES_P,
                                         DATACREDITO_P,
                                         VALORSOLICITADO_P,
                                         EXCEPCIONAL_P,
                                         RESULTADO_P,
                                         RETORNO_P);
  
END PR_EMP_REGRA_25666;
/
