//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNCEF.Planus.WebEmprestimo.Web.Paginas.Tratamentos.Individual {
    
    
    public partial class PopupConfirmacao {
        
        /// <summary>
        /// divOrigemRecurso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divOrigemRecurso;
        
        /// <summary>
        /// caixaTextoOrigemRecurso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaTexto caixaTextoOrigemRecurso;
        
        /// <summary>
        /// botaoOk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoOk botaoOk;
        
        /// <summary>
        /// botaoCancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoCancelar botaoCancelar;
    }
}
