-- OWNER --> LOGPLANUS    

-- Atualizando a Trigger 

CREATE or replace TRIGGER CM.TUDLOGALT_CONTRATOORIG
BEFORE UPDATE OF
IDCONTRATO
,NOMECONTRATO
,IDRESERVAORCAMEN
,IDTELEFONE
,CODPORTFORMA
,IDENDCOBRANCA
,CODCENTRORESPON
,IDPESSOA
,IDENDCORRESPON
,IDENDENTREGA
,UNIDNEGOC
,IDCONTATO
,IDFORCLI
,MOECODIGO
,IDRESPONSAVEL
,TIPOCONTRATO
,DESCRICAOCONTRATO
,DATAASSINATURA
,VALORBASECONTRATO
,DATABASECONTRATO
,DATAPREVENCERRA
,PRAZODENUNCIA
,CODCONTRATOEMPR
,FLGEMPENHO
,DATAEFETENCERRA
,MOTIVOENCERRA
,FLGFIMCONTRATO
,CODTIPDOC
,RENOVACAO
,OBSERVACAO
,AVISO
,TRGDTINCLUSAO
,TRGUSERINCLUSAO
,IDADITAMENTO
,IDTIPOPROCESSORAD
,FLGGERANOTADEB
,DATAINICIO
,DATA_ULTIMA_COTACAO
,VALOR_ORCADO
,FLGTIPOVALORBASE
,FLGCONTRATACAO
,IDENTIFICADOR
,JUSTIFOPCAONAOSEAPLICA  -- WO13506 - Paulo Nobre
OR DELETE ON CM.CONTRATOORIG
FOR EACH ROW
DECLARE
vTipoOperacao CHAR(1);
BEGIN
IF deleting THEN
vTipoOperacao := 'D';
END IF;
IF updating THEN
vTipoOperacao := 'A';
END IF;
IF  (:NEW.IDCONTRATO <> :OLD.IDCONTRATO) OR
(:NEW.IDCONTRATO IS NULL AND :OLD.IDCONTRATO IS NOT NULL) OR
(:NEW.IDCONTRATO IS NOT NULL AND :OLD.IDCONTRATO IS NULL)
OR (:NEW.NOMECONTRATO <> :OLD.NOMECONTRATO) OR
(:NEW.NOMECONTRATO IS NULL AND :OLD.NOMECONTRATO IS NOT NULL) OR
(:NEW.NOMECONTRATO IS NOT NULL AND :OLD.NOMECONTRATO IS NULL)
OR (:NEW.IDRESERVAORCAMEN <> :OLD.IDRESERVAORCAMEN) OR
(:NEW.IDRESERVAORCAMEN IS NULL AND :OLD.IDRESERVAORCAMEN IS NOT NULL) OR
(:NEW.IDRESERVAORCAMEN IS NOT NULL AND :OLD.IDRESERVAORCAMEN IS NULL)
OR (:NEW.IDTELEFONE <> :OLD.IDTELEFONE) OR
(:NEW.IDTELEFONE IS NULL AND :OLD.IDTELEFONE IS NOT NULL) OR
(:NEW.IDTELEFONE IS NOT NULL AND :OLD.IDTELEFONE IS NULL)
OR (:NEW.CODPORTFORMA <> :OLD.CODPORTFORMA) OR
(:NEW.CODPORTFORMA IS NULL AND :OLD.CODPORTFORMA IS NOT NULL) OR
(:NEW.CODPORTFORMA IS NOT NULL AND :OLD.CODPORTFORMA IS NULL)
OR (:NEW.IDENDCOBRANCA <> :OLD.IDENDCOBRANCA) OR
(:NEW.IDENDCOBRANCA IS NULL AND :OLD.IDENDCOBRANCA IS NOT NULL) OR
(:NEW.IDENDCOBRANCA IS NOT NULL AND :OLD.IDENDCOBRANCA IS NULL)
OR (:NEW.CODCENTRORESPON <> :OLD.CODCENTRORESPON) OR
(:NEW.CODCENTRORESPON IS NULL AND :OLD.CODCENTRORESPON IS NOT NULL) OR
(:NEW.CODCENTRORESPON IS NOT NULL AND :OLD.CODCENTRORESPON IS NULL)
OR (:NEW.IDPESSOA <> :OLD.IDPESSOA) OR
(:NEW.IDPESSOA IS NULL AND :OLD.IDPESSOA IS NOT NULL) OR
(:NEW.IDPESSOA IS NOT NULL AND :OLD.IDPESSOA IS NULL)
OR (:NEW.IDENDCORRESPON <> :OLD.IDENDCORRESPON) OR
(:NEW.IDENDCORRESPON IS NULL AND :OLD.IDENDCORRESPON IS NOT NULL) OR
(:NEW.IDENDCORRESPON IS NOT NULL AND :OLD.IDENDCORRESPON IS NULL)
OR (:NEW.IDENDENTREGA <> :OLD.IDENDENTREGA) OR
(:NEW.IDENDENTREGA IS NULL AND :OLD.IDENDENTREGA IS NOT NULL) OR
(:NEW.IDENDENTREGA IS NOT NULL AND :OLD.IDENDENTREGA IS NULL)
OR (:NEW.UNIDNEGOC <> :OLD.UNIDNEGOC) OR
(:NEW.UNIDNEGOC IS NULL AND :OLD.UNIDNEGOC IS NOT NULL) OR
(:NEW.UNIDNEGOC IS NOT NULL AND :OLD.UNIDNEGOC IS NULL)
OR (:NEW.IDCONTATO <> :OLD.IDCONTATO) OR
(:NEW.IDCONTATO IS NULL AND :OLD.IDCONTATO IS NOT NULL) OR
(:NEW.IDCONTATO IS NOT NULL AND :OLD.IDCONTATO IS NULL)
OR (:NEW.IDFORCLI <> :OLD.IDFORCLI) OR
(:NEW.IDFORCLI IS NULL AND :OLD.IDFORCLI IS NOT NULL) OR
(:NEW.IDFORCLI IS NOT NULL AND :OLD.IDFORCLI IS NULL)
OR (:NEW.MOECODIGO <> :OLD.MOECODIGO) OR
(:NEW.MOECODIGO IS NULL AND :OLD.MOECODIGO IS NOT NULL) OR
(:NEW.MOECODIGO IS NOT NULL AND :OLD.MOECODIGO IS NULL)
OR (:NEW.IDRESPONSAVEL <> :OLD.IDRESPONSAVEL) OR
(:NEW.IDRESPONSAVEL IS NULL AND :OLD.IDRESPONSAVEL IS NOT NULL) OR
(:NEW.IDRESPONSAVEL IS NOT NULL AND :OLD.IDRESPONSAVEL IS NULL)
OR (:NEW.TIPOCONTRATO <> :OLD.TIPOCONTRATO) OR
(:NEW.TIPOCONTRATO IS NULL AND :OLD.TIPOCONTRATO IS NOT NULL) OR
(:NEW.TIPOCONTRATO IS NOT NULL AND :OLD.TIPOCONTRATO IS NULL)
OR (:NEW.DESCRICAOCONTRATO <> :OLD.DESCRICAOCONTRATO) OR
(:NEW.DESCRICAOCONTRATO IS NULL AND :OLD.DESCRICAOCONTRATO IS NOT NULL) OR
(:NEW.DESCRICAOCONTRATO IS NOT NULL AND :OLD.DESCRICAOCONTRATO IS NULL)
OR (:NEW.DATAASSINATURA <> :OLD.DATAASSINATURA) OR
(:NEW.DATAASSINATURA IS NULL AND :OLD.DATAASSINATURA IS NOT NULL) OR
(:NEW.DATAASSINATURA IS NOT NULL AND :OLD.DATAASSINATURA IS NULL)
OR (:NEW.VALORBASECONTRATO <> :OLD.VALORBASECONTRATO) OR
(:NEW.VALORBASECONTRATO IS NULL AND :OLD.VALORBASECONTRATO IS NOT NULL) OR
(:NEW.VALORBASECONTRATO IS NOT NULL AND :OLD.VALORBASECONTRATO IS NULL)
OR (:NEW.DATABASECONTRATO <> :OLD.DATABASECONTRATO) OR
(:NEW.DATABASECONTRATO IS NULL AND :OLD.DATABASECONTRATO IS NOT NULL) OR
(:NEW.DATABASECONTRATO IS NOT NULL AND :OLD.DATABASECONTRATO IS NULL)
OR (:NEW.DATAPREVENCERRA <> :OLD.DATAPREVENCERRA) OR
(:NEW.DATAPREVENCERRA IS NULL AND :OLD.DATAPREVENCERRA IS NOT NULL) OR
(:NEW.DATAPREVENCERRA IS NOT NULL AND :OLD.DATAPREVENCERRA IS NULL)
OR (:NEW.PRAZODENUNCIA <> :OLD.PRAZODENUNCIA) OR
(:NEW.PRAZODENUNCIA IS NULL AND :OLD.PRAZODENUNCIA IS NOT NULL) OR
(:NEW.PRAZODENUNCIA IS NOT NULL AND :OLD.PRAZODENUNCIA IS NULL)
OR (:NEW.CODCONTRATOEMPR <> :OLD.CODCONTRATOEMPR) OR
(:NEW.CODCONTRATOEMPR IS NULL AND :OLD.CODCONTRATOEMPR IS NOT NULL) OR
(:NEW.CODCONTRATOEMPR IS NOT NULL AND :OLD.CODCONTRATOEMPR IS NULL)
OR (:NEW.FLGEMPENHO <> :OLD.FLGEMPENHO) OR
(:NEW.FLGEMPENHO IS NULL AND :OLD.FLGEMPENHO IS NOT NULL) OR
(:NEW.FLGEMPENHO IS NOT NULL AND :OLD.FLGEMPENHO IS NULL)
OR (:NEW.DATAEFETENCERRA <> :OLD.DATAEFETENCERRA) OR
(:NEW.DATAEFETENCERRA IS NULL AND :OLD.DATAEFETENCERRA IS NOT NULL) OR
(:NEW.DATAEFETENCERRA IS NOT NULL AND :OLD.DATAEFETENCERRA IS NULL)
OR (:NEW.MOTIVOENCERRA <> :OLD.MOTIVOENCERRA) OR
(:NEW.MOTIVOENCERRA IS NULL AND :OLD.MOTIVOENCERRA IS NOT NULL) OR
(:NEW.MOTIVOENCERRA IS NOT NULL AND :OLD.MOTIVOENCERRA IS NULL)
OR (:NEW.FLGFIMCONTRATO <> :OLD.FLGFIMCONTRATO) OR
(:NEW.FLGFIMCONTRATO IS NULL AND :OLD.FLGFIMCONTRATO IS NOT NULL) OR
(:NEW.FLGFIMCONTRATO IS NOT NULL AND :OLD.FLGFIMCONTRATO IS NULL)
OR (:NEW.CODTIPDOC <> :OLD.CODTIPDOC) OR
(:NEW.CODTIPDOC IS NULL AND :OLD.CODTIPDOC IS NOT NULL) OR
(:NEW.CODTIPDOC IS NOT NULL AND :OLD.CODTIPDOC IS NULL)
OR (:NEW.RENOVACAO <> :OLD.RENOVACAO) OR
(:NEW.RENOVACAO IS NULL AND :OLD.RENOVACAO IS NOT NULL) OR
(:NEW.RENOVACAO IS NOT NULL AND :OLD.RENOVACAO IS NULL)
OR (:NEW.OBSERVACAO <> :OLD.OBSERVACAO) OR
(:NEW.OBSERVACAO IS NULL AND :OLD.OBSERVACAO IS NOT NULL) OR
(:NEW.OBSERVACAO IS NOT NULL AND :OLD.OBSERVACAO IS NULL)
OR (:NEW.AVISO <> :OLD.AVISO) OR
(:NEW.AVISO IS NULL AND :OLD.AVISO IS NOT NULL) OR
(:NEW.AVISO IS NOT NULL AND :OLD.AVISO IS NULL)
OR (:NEW.TRGDTINCLUSAO <> :OLD.TRGDTINCLUSAO) OR
(:NEW.TRGDTINCLUSAO IS NULL AND :OLD.TRGDTINCLUSAO IS NOT NULL) OR
(:NEW.TRGDTINCLUSAO IS NOT NULL AND :OLD.TRGDTINCLUSAO IS NULL)
OR (:NEW.TRGUSERINCLUSAO <> :OLD.TRGUSERINCLUSAO) OR
(:NEW.TRGUSERINCLUSAO IS NULL AND :OLD.TRGUSERINCLUSAO IS NOT NULL) OR
(:NEW.TRGUSERINCLUSAO IS NOT NULL AND :OLD.TRGUSERINCLUSAO IS NULL)
OR (:NEW.IDADITAMENTO <> :OLD.IDADITAMENTO) OR
(:NEW.IDADITAMENTO IS NULL AND :OLD.IDADITAMENTO IS NOT NULL) OR
(:NEW.IDADITAMENTO IS NOT NULL AND :OLD.IDADITAMENTO IS NULL)
OR (:NEW.IDTIPOPROCESSORAD <> :OLD.IDTIPOPROCESSORAD) OR
(:NEW.IDTIPOPROCESSORAD IS NULL AND :OLD.IDTIPOPROCESSORAD IS NOT NULL) OR
(:NEW.IDTIPOPROCESSORAD IS NOT NULL AND :OLD.IDTIPOPROCESSORAD IS NULL)
OR (:NEW.FLGGERANOTADEB <> :OLD.FLGGERANOTADEB) OR
(:NEW.FLGGERANOTADEB IS NULL AND :OLD.FLGGERANOTADEB IS NOT NULL) OR
(:NEW.FLGGERANOTADEB IS NOT NULL AND :OLD.FLGGERANOTADEB IS NULL)
OR (:NEW.DATAINICIO <> :OLD.DATAINICIO) OR
(:NEW.DATAINICIO IS NULL AND :OLD.DATAINICIO IS NOT NULL) OR
(:NEW.DATAINICIO IS NOT NULL AND :OLD.DATAINICIO IS NULL)
OR (:NEW.DATA_ULTIMA_COTACAO <> :OLD.DATA_ULTIMA_COTACAO) OR
(:NEW.DATA_ULTIMA_COTACAO IS NULL AND :OLD.DATA_ULTIMA_COTACAO IS NOT NULL) OR
(:NEW.DATA_ULTIMA_COTACAO IS NOT NULL AND :OLD.DATA_ULTIMA_COTACAO IS NULL)
OR (:NEW.VALOR_ORCADO <> :OLD.VALOR_ORCADO) OR
(:NEW.VALOR_ORCADO IS NULL AND :OLD.VALOR_ORCADO IS NOT NULL) OR
(:NEW.VALOR_ORCADO IS NOT NULL AND :OLD.VALOR_ORCADO IS NULL)
OR (:NEW.FLGTIPOVALORBASE <> :OLD.FLGTIPOVALORBASE) OR
(:NEW.FLGTIPOVALORBASE IS NULL AND :OLD.FLGTIPOVALORBASE IS NOT NULL) OR
(:NEW.FLGTIPOVALORBASE IS NOT NULL AND :OLD.FLGTIPOVALORBASE IS NULL)
OR (:NEW.FLGCONTRATACAO <> :OLD.FLGCONTRATACAO) OR
(:NEW.FLGCONTRATACAO IS NULL AND :OLD.FLGCONTRATACAO IS NOT NULL) OR
(:NEW.FLGCONTRATACAO IS NOT NULL AND :OLD.FLGCONTRATACAO IS NULL)
OR (:NEW.IDENTIFICADOR <> :OLD.IDENTIFICADOR) OR
(:NEW.IDENTIFICADOR IS NULL AND :OLD.IDENTIFICADOR IS NOT NULL) OR
(:NEW.IDENTIFICADOR IS NOT NULL AND :OLD.IDENTIFICADOR IS NULL)
-- Paulo Nobre - WO13506 - Inicio 
OR (:NEW.JUSTIFOPCAONAOSEAPLICA <> :OLD.JUSTIFOPCAONAOSEAPLICA) OR
(:NEW.JUSTIFOPCAONAOSEAPLICA IS NULL AND :OLD.JUSTIFOPCAONAOSEAPLICA IS NOT NULL) OR
(:NEW.JUSTIFOPCAONAOSEAPLICA IS NOT NULL AND :OLD.JUSTIFOPCAONAOSEAPLICA IS NULL)
-- Paulo Nobre - WO13506 - Fim
THEN
INSERT INTO LOGPLANUS.LOG_PLANUS_CONTRATOORIG (IDLOGCONTRATOORIG,
IDCONTRATO,
NOMECONTRATO,
IDRESERVAORCAMEN,
IDTELEFONE,
CODPORTFORMA,
IDENDCOBRANCA,
CODCENTRORESPON,
IDPESSOA,
IDENDCORRESPON,
IDENDENTREGA,
UNIDNEGOC,
IDCONTATO,
IDFORCLI,
MOECODIGO,
IDRESPONSAVEL,
TIPOCONTRATO,
DESCRICAOCONTRATO,
DATAASSINATURA,
VALORBASECONTRATO,
DATABASECONTRATO,
DATAPREVENCERRA,
PRAZODENUNCIA,
CODCONTRATOEMPR,
FLGEMPENHO,
DATAEFETENCERRA,
MOTIVOENCERRA,
FLGFIMCONTRATO,
CODTIPDOC,
RENOVACAO,
OBSERVACAO,
AVISO,
TRGDTINCLUSAO,
TRGUSERINCLUSAO,
IDADITAMENTO,
IDTIPOPROCESSORAD,
FLGGERANOTADEB,
DATAINICIO,
DATA_ULTIMA_COTACAO,
VALOR_ORCADO,
FLGTIPOVALORBASE,
FLGCONTRATACAO,
IDENTIFICADOR,
ROWIDORIGEM,
Operacao,
TRGDTALTERACAO,
TRGUSERALTERACAO,
JUSTIFOPCAONAOSEAPLICA  -- WO13506 - Paulo Nobre
)
VALUES (LOGPLANUS.SEQLOGPLANUS_CONTRATOORIG.NEXTVAL,
:OLD.IDCONTRATO,
:OLD.NOMECONTRATO,
:OLD.IDRESERVAORCAMEN,
:OLD.IDTELEFONE,
:OLD.CODPORTFORMA,
:OLD.IDENDCOBRANCA,
:OLD.CODCENTRORESPON,
:OLD.IDPESSOA,
:OLD.IDENDCORRESPON,
:OLD.IDENDENTREGA,
:OLD.UNIDNEGOC,
:OLD.IDCONTATO,
:OLD.IDFORCLI,
:OLD.MOECODIGO,
:OLD.IDRESPONSAVEL,
:OLD.TIPOCONTRATO,
:OLD.DESCRICAOCONTRATO,
:OLD.DATAASSINATURA,
:OLD.VALORBASECONTRATO,
:OLD.DATABASECONTRATO,
:OLD.DATAPREVENCERRA,
:OLD.PRAZODENUNCIA,
:OLD.CODCONTRATOEMPR,
:OLD.FLGEMPENHO,
:OLD.DATAEFETENCERRA,
:OLD.MOTIVOENCERRA,
:OLD.FLGFIMCONTRATO,
:OLD.CODTIPDOC,
:OLD.RENOVACAO,
:OLD.OBSERVACAO,
:OLD.AVISO,
:OLD.TRGDTINCLUSAO,
:OLD.TRGUSERINCLUSAO,
:OLD.IDADITAMENTO,
:OLD.IDTIPOPROCESSORAD,
:OLD.FLGGERANOTADEB,
:OLD.DATAINICIO,
:OLD.DATA_ULTIMA_COTACAO,
:OLD.VALOR_ORCADO,
:OLD.FLGTIPOVALORBASE,
:OLD.FLGCONTRATACAO,
:OLD.IDENTIFICADOR,
:OLD.ROWID,
vTipoOperacao,
SYSDATE,
USER,
:OLD.JUSTIFOPCAONAOSEAPLICA  -- WO13506 - Paulo Nobre
);
END IF;
END;