CREATE OR REPLACE TRIGGER CM.TUDLOGALT_PADRAORATEIOFLUXO
BEFORE UPDATE OF
IDPADRAORATEIOFLUXO
,IDGRUPORATEIOFLUXO
,IDEMPRESAPROP
,UNIDNEGOC
,CODCENTRORESPON
,IDFLUXOCAIXA
,CODLINHAFLUXO
,RECPAG
,CODTIPRECDES
,IDSEGREGACRITER
,IDPATRO
,IDPLANOPREV
,CODTIPDOC
,MOECODIGO
,PERCENTRATEIO
,TRGDTINCLUSAO
,TRGUSERINCLUSAO
,IDPROGRAMA 
,CODCENTROCUSTO
OR DELETE ON PADRAORATEIOFLUXO
FOR EACH ROW
DECLARE
vTipoOperacao CHAR(1);
BEGIN
IF deleting THEN
vTipoOperacao := 'D';
END IF;
IF updating THEN
vTipoOperacao := 'A';
END IF;
IF  (:NEW.IDPADRAORATEIOFLUXO <> :OLD.IDPADRAORATEIOFLUXO) OR
(:NEW.IDPADRAORATEIOFLUXO IS NULL AND :OLD.IDPADRAORATEIOFLUXO IS NOT NULL) OR
(:NEW.IDPADRAORATEIOFLUXO IS NOT NULL AND :OLD.IDPADRAORATEIOFLUXO IS NULL)
OR (:NEW.IDGRUPORATEIOFLUXO <> :OLD.IDGRUPORATEIOFLUXO) OR
(:NEW.IDGRUPORATEIOFLUXO IS NULL AND :OLD.IDGRUPORATEIOFLUXO IS NOT NULL) OR
(:NEW.IDGRUPORATEIOFLUXO IS NOT NULL AND :OLD.IDGRUPORATEIOFLUXO IS NULL)
OR (:NEW.IDEMPRESAPROP <> :OLD.IDEMPRESAPROP) OR
(:NEW.IDEMPRESAPROP IS NULL AND :OLD.IDEMPRESAPROP IS NOT NULL) OR
(:NEW.IDEMPRESAPROP IS NOT NULL AND :OLD.IDEMPRESAPROP IS NULL)
OR (:NEW.UNIDNEGOC <> :OLD.UNIDNEGOC) OR
(:NEW.UNIDNEGOC IS NULL AND :OLD.UNIDNEGOC IS NOT NULL) OR
(:NEW.UNIDNEGOC IS NOT NULL AND :OLD.UNIDNEGOC IS NULL)
OR (:NEW.CODCENTRORESPON <> :OLD.CODCENTRORESPON) OR
(:NEW.CODCENTRORESPON IS NULL AND :OLD.CODCENTRORESPON IS NOT NULL) OR
(:NEW.CODCENTRORESPON IS NOT NULL AND :OLD.CODCENTRORESPON IS NULL)
OR (:NEW.IDFLUXOCAIXA <> :OLD.IDFLUXOCAIXA) OR
(:NEW.IDFLUXOCAIXA IS NULL AND :OLD.IDFLUXOCAIXA IS NOT NULL) OR
(:NEW.IDFLUXOCAIXA IS NOT NULL AND :OLD.IDFLUXOCAIXA IS NULL)
OR (:NEW.CODLINHAFLUXO <> :OLD.CODLINHAFLUXO) OR
(:NEW.CODLINHAFLUXO IS NULL AND :OLD.CODLINHAFLUXO IS NOT NULL) OR
(:NEW.CODLINHAFLUXO IS NOT NULL AND :OLD.CODLINHAFLUXO IS NULL)
OR (:NEW.RECPAG <> :OLD.RECPAG) OR
(:NEW.RECPAG IS NULL AND :OLD.RECPAG IS NOT NULL) OR
(:NEW.RECPAG IS NOT NULL AND :OLD.RECPAG IS NULL)
OR (:NEW.CODTIPRECDES <> :OLD.CODTIPRECDES) OR
(:NEW.CODTIPRECDES IS NULL AND :OLD.CODTIPRECDES IS NOT NULL) OR
(:NEW.CODTIPRECDES IS NOT NULL AND :OLD.CODTIPRECDES IS NULL)
OR (:NEW.IDSEGREGACRITER <> :OLD.IDSEGREGACRITER) OR
(:NEW.IDSEGREGACRITER IS NULL AND :OLD.IDSEGREGACRITER IS NOT NULL) OR
(:NEW.IDSEGREGACRITER IS NOT NULL AND :OLD.IDSEGREGACRITER IS NULL)
OR (:NEW.IDPATRO <> :OLD.IDPATRO) OR
(:NEW.IDPATRO IS NULL AND :OLD.IDPATRO IS NOT NULL) OR
(:NEW.IDPATRO IS NOT NULL AND :OLD.IDPATRO IS NULL)
OR (:NEW.IDPLANOPREV <> :OLD.IDPLANOPREV) OR
(:NEW.IDPLANOPREV IS NULL AND :OLD.IDPLANOPREV IS NOT NULL) OR
(:NEW.IDPLANOPREV IS NOT NULL AND :OLD.IDPLANOPREV IS NULL)
OR (:NEW.CODTIPDOC <> :OLD.CODTIPDOC) OR
(:NEW.CODTIPDOC IS NULL AND :OLD.CODTIPDOC IS NOT NULL) OR
(:NEW.CODTIPDOC IS NOT NULL AND :OLD.CODTIPDOC IS NULL)
OR (:NEW.MOECODIGO <> :OLD.MOECODIGO) OR
(:NEW.MOECODIGO IS NULL AND :OLD.MOECODIGO IS NOT NULL) OR
(:NEW.MOECODIGO IS NOT NULL AND :OLD.MOECODIGO IS NULL)
OR (:NEW.PERCENTRATEIO <> :OLD.PERCENTRATEIO) OR
(:NEW.PERCENTRATEIO IS NULL AND :OLD.PERCENTRATEIO IS NOT NULL) OR
(:NEW.PERCENTRATEIO IS NOT NULL AND :OLD.PERCENTRATEIO IS NULL)
OR (:NEW.TRGDTINCLUSAO <> :OLD.TRGDTINCLUSAO) OR
(:NEW.TRGDTINCLUSAO IS NULL AND :OLD.TRGDTINCLUSAO IS NOT NULL) OR
(:NEW.TRGDTINCLUSAO IS NOT NULL AND :OLD.TRGDTINCLUSAO IS NULL)
OR (:NEW.TRGUSERINCLUSAO <> :OLD.TRGUSERINCLUSAO) OR
(:NEW.TRGUSERINCLUSAO IS NULL AND :OLD.TRGUSERINCLUSAO IS NOT NULL) OR
(:NEW.TRGUSERINCLUSAO IS NOT NULL AND :OLD.TRGUSERINCLUSAO IS NULL)
OR (:NEW.IDPROGRAMA <> :OLD.IDPROGRAMA) OR
(:NEW.IDPROGRAMA IS NULL AND :OLD.IDPROGRAMA IS NOT NULL) OR
(:NEW.IDPROGRAMA IS NOT NULL AND :OLD.IDPROGRAMA IS NULL)
OR (:NEW.CODCENTROCUSTO <> :OLD.CODCENTROCUSTO) OR
(:NEW.CODCENTROCUSTO IS NULL AND :OLD.CODCENTROCUSTO IS NOT NULL) OR
(:NEW.CODCENTROCUSTO IS NOT NULL AND :OLD.CODCENTROCUSTO IS NULL)
THEN
INSERT INTO LOGPLANUS.LOG_PLANUS_PADRAORATEIOFLUXO (IDLOGPADRAORATEIOFLUXO,
IDPADRAORATEIOFLUXO,
IDGRUPORATEIOFLUXO,
IDEMPRESAPROP,
UNIDNEGOC,
CODCENTRORESPON,
IDFLUXOCAIXA,
CODLINHAFLUXO,
RECPAG,
CODTIPRECDES,
IDSEGREGACRITER,
IDPATRO,
IDPLANOPREV,
CODTIPDOC,
MOECODIGO,
PERCENTRATEIO,
TRGDTINCLUSAO,
TRGUSERINCLUSAO,
ROWIDORIGEM,
Operacao,
TRGDTALTERACAO,
TRGUSERALTERACAO,
IDPROGRAMA,
CODCENTROCUSTO
)
VALUES (LOGPLANUS.SEQLOGPLANUS_PADRAORATEIOFLUXO.NEXTVAL,
:OLD.IDPADRAORATEIOFLUXO,
:OLD.IDGRUPORATEIOFLUXO,
:OLD.IDEMPRESAPROP,
:OLD.UNIDNEGOC,
:OLD.CODCENTRORESPON,
:OLD.IDFLUXOCAIXA,
:OLD.CODLINHAFLUXO,
:OLD.RECPAG,
:OLD.CODTIPRECDES,
:OLD.IDSEGREGACRITER,
:OLD.IDPATRO,
:OLD.IDPLANOPREV,
:OLD.CODTIPDOC,
:OLD.MOECODIGO,
:OLD.PERCENTRATEIO,
:OLD.TRGDTINCLUSAO,
:OLD.TRGUSERINCLUSAO,
:OLD.ROWID,
vTipoOperacao,
SYSDATE,
USER,
:OLD.IDPROGRAMA,
:OLD.CODCENTROCUSTO
);
END IF;
END;
