ALTER TABLE CM.PADRAORATEIOFLUXO ADD IDPROGRAMA NUMBER;
ALTER TABLE CM.PADRAORATEIOFLUXO ADD CODCENTROCUSTO CHAR(10);

COMMENT ON COLUMN CM.PADRAORATEIOFLUXO.IDPROGRAMA IS 'Identificador do Programa Previdenciário';
COMMENT ON COLUMN CM.PADRAORATEIOFLUXO.CODCENTROCUSTO IS 'Código do Centro de Custo.';