//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNCEF.Planus.WebEmprestimo.Web.Paginas.Tratamentos.Parametrizacao {
    
    
    public partial class Inclusao {
        
        /// <summary>
        /// aba1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.TituloPagina aba1;
        
        /// <summary>
        /// SecaoParametro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.SecaoFormulario SecaoParametro;
        
        /// <summary>
        /// updatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updatePanel;
        
        /// <summary>
        /// caixaSelecaoTipoProposta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList caixaSelecaoTipoProposta;
        
        /// <summary>
        /// rfvTipoProposta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTipoProposta;
        
        /// <summary>
        /// txtDataInicio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaData txtDataInicio;
        
        /// <summary>
        /// rfvDataInicio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDataInicio;
        
        /// <summary>
        /// txtDataFim control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaData txtDataFim;
        
        /// <summary>
        /// rfvDataFim control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDataFim;
        
        /// <summary>
        /// botaoSalvar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoSalvar botaoSalvar;
        
        /// <summary>
        /// botaoCancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoCancelar botaoCancelar;
        
        /// <summary>
        /// botaoSair control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoSair botaoSair;
        
        /// <summary>
        /// SumarioValidacao1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.SumarioValidacao SumarioValidacao1;
        
        /// <summary>
        /// CustomValidatorParametros control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CustomValidator CustomValidatorParametros;
    }
}
