//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNCEF.Planus.WebEmprestimo.Web.ServicoAssinaturaContrato {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoAssinaturaContrato.ProtonSoap")]
    public interface ProtonSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornaCaminhoArquivoDigital", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RetornaCaminhoArquivoDigital(string txt_numero, string cod_copia, string txt_documento_tipo, string txt_matricula, string txt_nome);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProtonSoapChannel : FUNCEF.Planus.WebEmprestimo.Web.ServicoAssinaturaContrato.ProtonSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProtonSoapClient : System.ServiceModel.ClientBase<FUNCEF.Planus.WebEmprestimo.Web.ServicoAssinaturaContrato.ProtonSoap>, FUNCEF.Planus.WebEmprestimo.Web.ServicoAssinaturaContrato.ProtonSoap {
        
        public ProtonSoapClient() {
        }
        
        public ProtonSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProtonSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProtonSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProtonSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet RetornaCaminhoArquivoDigital(string txt_numero, string cod_copia, string txt_documento_tipo, string txt_matricula, string txt_nome) {
            return base.Channel.RetornaCaminhoArquivoDigital(txt_numero, cod_copia, txt_documento_tipo, txt_matricula, txt_nome);
        }
    }
}
