{*******************************************************}
{                                                       }
{ Padrões de Desenvolvimento                            }
{ Copyright © 1998,2002 - CM Soluções Informática       }
{                                                       }
{ - Atualização para o padrão MT (3 Camadas)            }
{                                                       }
{ Analista Responsável: Gustavo Viegas                  }
{ Atualizado Em: 10/04/2002                             }
{                                                       }
{*******************************************************}
KEY_ALIAS_SERVIDOR = 'Alias Servidor';
KEY_DRIVER_SERVIDOR = 'Driver Servidor';
KEY_ALIAS_SERVIDOR_REMOTO = 'Alias Servidor Remoto';
KEY_DRIVER_SERVIDOR_REMOTO = 'Driver Servidor Remoto';
KEY_CONNECTION_SIDE = 'Connection Side';
KEY_CONNECTION_TYPE = 'Connection Type';
KEY_MIDLEWARE_CONNECTION = 'Midle Ware Connection';
KEY_WEB_URL = 'Web Url';
KEY_DCOM_COMPUTERNAME = 'DCOM Computer Name';
KEY_SOCKET_HOST = 'Socket HOST';
KEY_LANGDRIVER = 'LANGDRIVER';
KEY_TIPO_SPLASH = 'TipoSplash';
KEY_IDIOMA_ATIVO = 'Idioma ativo';
KEY_DIR_VERSAO = 'Diretorio Versao';
KEY_NOME_SERVIDOR = 'Nome Servidor';
KEY_NOME_SERVIDOR_SECUNDARIO = 'Nome Servidor Secundario';
KEY_SHOWPARAM = 'Exibe tela de parâmetros do Sistema';
KEY_INSTANCIAS = 'Permite execucao multipla'; 


