<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContabPOC.Application\ContabPOC.Application.csproj" />
    <ProjectReference Include="..\ContabPOC.Infrastructure\ContabPOC.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- FUNCEF packages usando feed local -->
    <PackageReference Include="FUNCEF.Essenciais" />
    <PackageReference Include="FUNCEF.Autenticacao" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

</Project>
