//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNCEF.Planus.WebEmprestimo.Web.Paginas.CicloNormal.Emprestimo
{


    public partial class PopupRenegociacao
    {

        /// <summary>
        /// hdfScroll control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdfScroll;

        /// <summary>
        /// hdfScrollLeft control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdfScrollLeft;

        /// <summary>
        /// updatePanel12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updatePanel12;

        /// <summary>
        /// caixaNumericaValorSomaUltimasPrestacoes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaNumerica caixaNumericaValorSomaUltimasPrestacoes;

        /// <summary>
        /// repeaterContratosRefinanciamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater repeaterContratosRefinanciamento;

        /// <summary>
        /// caixaNumericaValorTotalParcelasQuitar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaNumerica caixaNumericaValorTotalParcelasQuitar;

        /// <summary>
        /// caixaNumericaValorSolicitadoRefinanciamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaNumerica caixaNumericaValorSolicitadoRefinanciamento;

        /// <summary>
        /// caixaNumericaValorAmortizar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaNumerica caixaNumericaValorAmortizar;

        /// <summary>
        /// caixaNumericaFGQC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaNumerica caixaNumericaFGQC;

        /// <summary>
        /// caixaNumericaIOF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaNumerica caixaNumericaIOF;

        /// <summary>
        /// caixaNumericTxAdm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaNumerica caixaNumericTxAdm;

        /// <summary>
        /// CaixaNumericaTotalAmortizar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.CaixaNumerica CaixaNumericaTotalAmortizar;

        /// <summary>
        /// checkBoxSelecionarTodas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkBoxSelecionarTodas;

        /// <summary>
        /// rdbPDF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputRadioButton rdbPDF;

        /// <summary>
        /// rdbExcel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputRadioButton rdbExcel;

        /// <summary>
        /// btnOKModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoOk btnOKModal;

        /// <summary>
        /// LoadIcon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputImage LoadIcon;

        /// <summary>
        /// BotaoAcao1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoAcao BotaoAcao1;

        /// <summary>
        /// BotaoGeraBoleto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoAcao BotaoGeraBoleto;

        /// <summary>
        /// botaoExportar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoAcao botaoExportar;

        /// <summary>
        /// botaoAtualizarCalculo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoAcao botaoAtualizarCalculo;

        /// <summary>
        /// botaoSair control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoSair botaoSair;
    }
}
