unit FDRelCartaReajuste;

//	-------------------------------------------------------------------------------------------------
//
//	   Desenho de Cartas de Reajuste
//
//	Autor             :  Telma
//	Data de Início    :
//	Data de Término   :
//
//	Modificações      :  17/10/2000  1) Herança alterada: desendente de frmCadastroCSImob;
//
//
//
// -------------------------------------------------------------------------------------------------

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  FCadastroCS, StdCtrls, Mask, wwdbedit, IvDictio, IvMulti, IvEMulti,
  MontaSelect, DBTables, Db, Wwdatsrc, Wwquery, TB97Ctls, MAHlpBtn,
  Buttons, TB97Tlbr, TB97, ExtCtrls, Menus,ppEndUsr, ppCache, ppDB, ppDBBDE,ppForms,
  ppComm, ppProd, ppClass, ppReport, ppPrnabl, ppCtrls, ppBands, Pptypes,
  ppDsgnCt, ppUtils, ppSubRpt, ppRuler, ppViewr, ppRegion, ppPrintr,
  ppTmplat, Printers, DBCtrls, Wwdbspin, FCadastroCSImob, FDRel, ppRelatv,
  ppDBPipe, CmEventosCadastro, ImgList;

type
  TfrmDesenhoRelCartaReajuste = class(TfrmDesenhoRel)
    qryIDCARTACOBRANCA: TFloatField;
    qryMODELOCARTA: TStringField;
    qryIDREPORTS: TFloatField;
    qryORIGEMCM: TFloatField;
    qryFLGTIPOCARTA: TStringField;
    qrySql: TwwQuery;
    qrySqlData_Atual: TStringField;
    qrySqlCABECALHO: TStringField;
    qrySqlNUMERO_CONTRATO: TStringField;
    qrySqlNOME_CONTRATO: TStringField;
    qrySqlVLR_ATUAL_CONTRATO: TFloatField;
    qrySqlVLR_ANT_CONTRATO: TFloatField;
    qrySqlCONINDICEREAJUSTE: TFloatField;
    qrySqlCONPROXREAJUSTE: TDateTimeField;
    qrySqlCONDATAREAJUSTE: TDateTimeField;
    qrySqlRS_LOCATARIO: TStringField;
    qrySqlNOME_CONTATO: TStringField;
    qrySqlINDICE_REAJUSTE: TStringField;
    qrySqlDIAS_VLR_ANTERIOR: TFloatField;
    qrySqlDIAS_VLR_POSTERIOR: TFloatField;
    qrySqlPERCENT_REAJUSTE_CALCULADO: TFloatField;
    qrySqlPERCENT_REAJUSTE_ACUMULADO: TFloatField;
    qrySqlMES_REAJUSTE: TStringField;
    qrySqlMES_ULT_REAJUSTE: TStringField;
    qrySqlMES_REAJUSTE_MENOS_UM: TStringField;
    qrySqlVLR_DIAS_ANTERIOR: TFloatField;
    qrySqlVLR_DIAS_POSTERIOR: TFloatField;
    qrySqlDIAS_MES: TFloatField;
    qrySqlVLR_TOTAL: TFloatField;
    qrySqlValorExtenso: TStringField;
    qrySqlValorExtensoTot: TStringField;
    qrySqlENDERECO: TStringField;

    // procedimentos definidos
    Procedure CmeCadastroFind(Sender: TObject);
    Procedure CmeCadastroInsert(Sender: TObject);
    Procedure CmeCadastroEdit(Sender: TObject);

    function GetCmCartaCob: string;
    procedure FormCreate(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure mnifilePrintToFileSetupClick(Sender: TObject);
    procedure mnifilePrintClick(Sender: TObject);
    procedure mnifilePageSetupClick(Sender: TObject);


  private { Private declarations }

  public { Public declarations }

  end;



var
  frmDesenhoRelCartaReajuste: TfrmDesenhoRelCartaReajuste;



implementation
{$R *.DFM}
uses
   uSistema, uDataBase, uMensErro, uFuncoesImob;



procedure TfrmDesenhoRelCartaReajuste.CmeCadastroFind(Sender: TObject);
begin
   inherited;

   if MontaSelect.RetornouValor then begin

      Screen.Cursor := crHourGlass;

      with qry do begin
         LimpaParametros(qry);
         ParamByName('PCARTACOBRANCA').asInteger := StrToInt(MontaSelect.ValoresChave[0]);
         Open;
      end;
      Screen.Cursor := crDefault;
   end;
end;



procedure TfrmDesenhoRelCartaReajuste.CmeCadastroInsert(Sender: TObject);
begin
   inherited;
   MemReports.Lines.Clear;
   MemReports.Lines.Text := GetCMCartaCob;
   MemReports.Lines.SaveToFile(Sistema.TempDir + ArqModelo);

   qryIdCartaCobranca.asFloat := LeUltRegistro(nil,'CARTACOBRANCA');
   qryIDREPORTS.asInteger     := LeUltRegistro(nil,'REPORTS');
   qryORIGEMCM.asInteger      := 0;
   qryFLGTIPOCARTA.asString   := 'J';
end;



procedure TfrmDesenhoRelCartaReajuste.CmeCadastroEdit(Sender: TObject);
begin
   inherited;

   qryReports.Close;

   if not(qryReports.Prepared) then qryReports.Prepare;
   qryReports.ParamByName('PREPORT').asInteger     := qryIDREPORTS.asInteger;
   qryReports.ParamByName('PORIGEMCM').asInteger   := qryORIGEMCM.asInteger;
   qryReports.Open;

   MemReports.Lines.Clear;
   MemReports.Lines.Text := qryReportsTEMPLATE.asString;
end;



function TfrmDesenhoRelCartaReajuste.GetCmCartaCob: string;
var
   sTemp : tStringList;
begin
   sTemp:= tStringList.Create;

   with sTemp do begin
      Clear;
      Add('object TppReport');
      Add('  DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('  PrinterSetup.BinName = ''Default''');
      Add('  PrinterSetup.DocumentName = ''PpModeloReport1''');
      Add('  PrinterSetup.PaperName = ''A4''');
      Add('  PrinterSetup.PrinterName = ''Default''');
      Add('  PrinterSetup.mmMarginBottom = 13229');
      Add('  PrinterSetup.mmMarginLeft = 6615');
      Add('  PrinterSetup.mmMarginRight = 6615');
      Add('  PrinterSetup.mmMarginTop = 13229');
      Add('  PrinterSetup.mmPaperHeight = 297127');
      Add('  PrinterSetup.mmPaperWidth = 210079');
      Add('  SaveAsTemplate = True');
      Add('  Template.FileName = ''C:\TEMP\CartaReajuste.tmp''');
      Add('  Template.Format = ftASCII');
      Add('  Units = utScreenPixels');
      Add('  AllowPrintToArchive = True');
      Add('  AllowPrintToFile = True');
      Add('  Language = lgPortugueseBrazil');
      Add('  Version = ''3.52''');
      Add('  mmColumnWidth = 197300');
      Add('  object ppDetailBand1: TppDetailBand');
      Add('    mmBottomOffset = 0');
      Add('    mmHeight = 191559');
      Add('    mmPrintPosition = 0');
      Add('    object rpCartaCobrancaLabel8: TppLabel');
      Add('      Caption = ''Prezado(s) Senhor(es),''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 10583');
      Add('      mmTop = 66146');
      Add('      mmWidth = 40746');
      Add('      BandType = 4');
      Add('    end');
      Add('    object rpCartaCobrancaLabel2: TppLabel');
      Add('      Caption = ''A''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 10583');
      Add('      mmTop = 35454');
      Add('      mmWidth = 2381');
      Add('      BandType = 4');
      Add('    end');
      Add('    object rpCartaCobrancaDBText1: TppDBText');
      Add('      AutoSize = True');
      Add('      DataField = ''RS_LOCATARIO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 10583');
      Add('      mmTop = 40746');
      Add('      mmWidth = 29898');
      Add('      BandType = 4');
      Add('    end');
      Add('    object rpCartaCobrancaLabel3: TppLabel');
      Add('      Caption = ''A/C:''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 10583');
      Add('      mmTop = 46038');
      Add('      mmWidth = 7408');
      Add('      BandType = 4');
      Add('    end');
      Add('    object rpCartaCobrancaDBText9: TppDBText');
      Add('      DataField = ''DATA_ATUAL''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 10');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4233');
      Add('      mmLeft = 10583');
      Add('      mmTop = 21167');
      Add('      mmWidth = 71438');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label1: TppLabel');
      Add('      Alignment = taRightJustify');
      Add('      AutoSize = False');
      Add('      Caption = ''Informamos que o valor do aluguel a partir de ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 28310');
      Add('      mmTop = 76729');
      Add('      mmWidth = 78317');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label2: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      AutoSize = False');
      Add('      Caption = '', relativo ao Contrato de Locação''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 124884');
      Add('      mmTop = 76729');
      Add('      mmWidth = 56621');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText2: TppDBText');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''NUMERO_CONTRATO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 14817');
      Add('      mmTop = 83873');
      Add('      mmWidth = 29369');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label3: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      AutoSize = False');
      Add('      Caption = '',  firmado entre esta Fundação e V.  Sª., é de R$ ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 43921');
      Add('      mmTop = 84138');
      Add('      mmWidth = 84138');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText3: TppDBText');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''VLR_ATUAL_CONTRATO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,###,##0.00;(###,###,##0.00)''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlue');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 127794');
      Add('      mmTop = 83873');
      Add('      mmWidth = 22225');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label4: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      AutoSize = False');
      Add('      Caption = ''abaixo discriminado e ficha de compensação em anexo:''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 10583');
      Add('      mmTop = 93927');
      Add('      mmWidth = 84402');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText24: TppDBText');
      Add('      AutoSize = True');
      Add('      DataField = ''NOME_CONTATO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 20108');
      Add('      mmTop = 46038');
      Add('      mmWidth = 34131');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText25: TppDBText');
      Add('      AutoSize = True');
      Add('      DataField = ''ENDERECO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 10583');
      Add('      mmTop = 51329');
      Add('      mmWidth = 22490');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label33: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      AutoSize = False');
      Add('      Caption = ''nº ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 10583');
      Add('      mmTop = 84138');
      Add('      mmWidth = 4498');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText1: TppDBText');
      Add('      Alignment = taCenter');
      Add('      DataField = ''MES_REAJUSTE''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlue');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 106363');
      Add('      mmTop = 76729');
      Add('      mmWidth = 18785');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText26: TppDBText');
      Add('      DataField = ''CABECALHO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 10');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4233');
      Add('      mmLeft = 10583');
      Add('      mmTop = 8467');
      Add('      mmWidth = 71438');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label5: TppLabel');
      Add('      Caption = ''Índice de reajuste contratual:  ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 29633');
      Add('      mmTop = 108744');
      Add('      mmWidth = 51329');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText4: TppDBText');
      Add('      DataField = ''INDICE_REAJUSTE''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 80698');
      Add('      mmTop = 108744');
      Add('      mmWidth = 14817');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label6: TppLabel');
      Add('      Caption = ''Índice acumulado de  ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 29633');
      Add('      mmTop = 114036');
      Add('      mmWidth = 37571');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText19: TppDBText');
      Add('      DataField = ''MES_ULT_REAJUSTE''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clWindowText');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 66940');
      Add('      mmTop = 114036');
      Add('      mmWidth = 18785');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label32: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      Caption = '' a ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 85461');
      Add('      mmTop = 114036');
      Add('      mmWidth = 4233');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText18: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''MES_REAJUSTE_MENOS_UM''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clWindowText');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 89429');
      Add('      mmTop = 114036');
      Add('      mmWidth = 18785');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label11: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      Caption = '' :  ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 107950');
      Add('      mmTop = 114036');
      Add('      mmWidth = 4233');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText5: TppDBText');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''PERCENT_REAJUSTE_CALCULADO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,##0.00 %;(###,##0.00) %''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 111919');
      Add('      mmTop = 114036');
      Add('      mmWidth = 14023');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label7: TppLabel');
      Add('      Caption = ''Valor corrigido: R$''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 29633');
      Add('      mmTop = 121444');
      Add('      mmWidth = 31750');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText27: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''VLR_ANT_CONTRATO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,###,##0.00;(###,###,##0.00)''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 61119');
      Add('      mmTop = 121444');
      Add('      mmWidth = 20638');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label14: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      AutoSize = False');
      Add('      Caption = '' + ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 81492');
      Add('      mmTop = 121444');
      Add('      mmWidth = 4498');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText7: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''PERCENT_REAJUSTE_CALCULADO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,##0.00 %;(###,##0.00) %''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 85725');
      Add('      mmTop = 121444');
      Add('      mmWidth = 14023');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label17: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      AutoSize = False');
      Add('      Caption = '' = R$ ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 99484');
      Add('      mmTop = 121444');
      Add('      mmWidth = 10848');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText9: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''VLR_ATUAL_CONTRATO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,###,##0.00;(###,###,##0.00)''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlue');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 110067');
      Add('      mmTop = 121444');
      Add('      mmWidth = 20638');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label8: TppLabel');
      Add('      AutoSize = False');
      Add('      Caption = ''VALOR DEVIDO PRO RATA PARA O MÊS DE ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlue');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 29633');
      Add('      mmTop = 126736');
      Add('      mmWidth = 84667');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText8: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      DataField = ''MES_REAJUSTE''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlue');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 114036');
      Add('      mmTop = 126736');
      Add('      mmWidth = 18785');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label15: TppLabel');
      Add('      AutoSize = False');
      Add('      Caption = ''( R$''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 29633');
      Add('      mmTop = 132292');
      Add('      mmWidth = 7408');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText10: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''VLR_ANT_CONTRATO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,###,##0.00;(###,###,##0.00)''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 36777');
      Add('      mmTop = 132292');
      Add('      mmWidth = 20638');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label22: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      AutoSize = False');
      Add('      Caption = ''  / ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 57150');
      Add('      mmTop = 132292');
      Add('      mmWidth = 4233');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText14: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taCenter');
      Add('      DataField = ''DIAS_MES''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''00''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clWindowText');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 61119');
      Add('      mmTop = 132292');
      Add('      mmWidth = 5556');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label23: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      AutoSize = False');
      Add('      Caption = '' ) x ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 66411');
      Add('      mmTop = 132292');
      Add('      mmWidth = 6350');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText22: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      DataField = ''DIAS_VLR_ANTERIOR''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''00''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clWindowText');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 72496');
      Add('      mmTop = 132292');
      Add('      mmWidth = 4763');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label30: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      AutoSize = False');
      Add('      Caption = '' = R$''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 76994');
      Add('      mmTop = 132292');
      Add('      mmWidth = 9525');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText16: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''VLR_DIAS_ANTERIOR''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,###,##0.00;(###,###,##0.00)''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clWindowText');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 86254');
      Add('      mmTop = 132292');
      Add('      mmWidth = 20638');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label12: TppLabel');
      Add('      AutoSize = False');
      Add('      Caption = ''( R$''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 29633');
      Add('      mmTop = 137584');
      Add('      mmWidth = 7408');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText11: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''VLR_ATUAL_CONTRATO''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,###,##0.00;(###,###,##0.00)''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 36777');
      Add('      mmTop = 137584');
      Add('      mmWidth = 20638');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label13: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      AutoSize = False');
      Add('      Caption = ''  / ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 57150');
      Add('      mmTop = 137584');
      Add('      mmWidth = 4233');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText15: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taCenter');
      Add('      DataField = ''DIAS_MES''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''00''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clWindowText');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 61119');
      Add('      mmTop = 137584');
      Add('      mmWidth = 5556');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label24: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      AutoSize = False');
      Add('      Caption = '' ) x ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 66411');
      Add('      mmTop = 137584');
      Add('      mmWidth = 6350');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText6: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      DataField = ''DIAS_VLR_POSTERIOR''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''00''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clWindowText');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 72496');
      Add('      mmTop = 137584');
      Add('      mmWidth = 4763');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label25: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      AutoSize = False');
      Add('      Caption = '' = R$''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 76994');
      Add('      mmTop = 137584');
      Add('      mmWidth = 9525');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText28: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''VLR_DIAS_POSTERIOR''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,###,##0.00;(###,###,##0.00)''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clWindowText');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 86254');
      Add('      mmTop = 137584');
      Add('      mmWidth = 20638');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label18: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      AutoSize = False');
      Add('      Caption = '' Valor a ser creditado em ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 29633');
      Add('      mmTop = 144727');
      Add('      mmWidth = 44186');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText12: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taCenter');
      Add('      DataField = ''MES_REAJUSTE''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clWindowText');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 73554');
      Add('      mmTop = 144727');
      Add('      mmWidth = 18785');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label26: TppLabel');
      Add('      AutoSize = False');
      Add('      Caption = '':  ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 92075');
      Add('      mmTop = 144727');
      Add('      mmWidth = 3175');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label19: TppLabel');
      Add('      AutoSize = False');
      Add('      Caption = ''( R$''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 29633');
      Add('      mmTop = 151077');
      Add('      mmWidth = 7408');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText17: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''VLR_DIAS_ANTERIOR''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,###,##0.00;(###,###,##0.00)''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 36777');
      Add('      mmTop = 151077');
      Add('      mmWidth = 20638');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label20: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      AutoSize = False');
      Add('      Caption = '' + ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 57150');
      Add('      mmTop = 151077');
      Add('      mmWidth = 4498');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label27: TppLabel');
      Add('      AutoSize = False');
      Add('      Caption = ''R$''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 61383');
      Add('      mmTop = 151077');
      Add('      mmWidth = 5027');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText20: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''VLR_DIAS_POSTERIOR''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,###,##0.00;(###,###,##0.00)''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 66146');
      Add('      mmTop = 151077');
      Add('      mmWidth = 20638');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label28: TppLabel');
      Add('      AutoSize = False');
      Add('      Caption = '' ) = R$''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 86519');
      Add('      mmTop = 151077');
      Add('      mmWidth = 11906');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText13: TppDBText');
      Add('      ShiftWithParent = True');
      Add('      Alignment = taRightJustify');
      Add('      DataField = ''VLR_TOTAL''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      DisplayFormat = ''###,###,##0.00;(###,###,##0.00)''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 98161');
      Add('      mmTop = 151077');
      Add('      mmWidth = 20638');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label9: TppLabel');
      Add('      Alignment = taRightJustify');
      Add('      Caption = ''Sendo o que se apresenta para o momento, subscrevemo nos.''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 10583');
      Add('      mmTop = 169334');
      Add('      mmWidth = 108744');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label10: TppLabel');
      Add('      Caption = ''Atenciosamente,''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 10583');
      Add('      mmTop = 176477');
      Add('      mmWidth = 30956');
      Add('      BandType = 4');
      Add('    end');
      Add('    object DBText21: TppDBText');
      Add('      DataField = ''ValorExtenso''');
      Add('      DataPipeline = frmDesenhoRelCartaReajuste.ppConsulta');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = [fsBold]');
      Add('      Transparent = True');
      Add('      mmHeight = 4763');
      Add('      mmLeft = 10583');
      Add('      mmTop = 88900');
      Add('      mmWidth = 150813');
      Add('      BandType = 4');
      Add('    end');
      Add('    object Label16: TppLabel');
      Add('      ShiftWithParent = True');
      Add('      AutoSize = False');
      Add('      Caption = '', conforme ''');
      Add('      Font.Charset = DEFAULT_CHARSET');
      Add('      Font.Color = clBlack');
      Add('      Font.Name = ''Arial''');
      Add('      Font.Size = 11');
      Add('      Font.Style = []');
      Add('      Transparent = True');
      Add('      mmHeight = 4498');
      Add('      mmLeft = 161396');
      Add('      mmTop = 89165');
      Add('      mmWidth = 19579');
      Add('      BandType = 4');
      Add('    end');
      Add('  end');
      Add('end');
   end;

   Result := sTemp.Text;
end;



procedure TfrmDesenhoRelCartaReajuste.FormCreate(Sender: TObject);
begin
   inherited;

   ArqModelo := 'CartaReajuste.tmp';

   if not(qry.Prepared) then qry.Prepare;
   if not(qryReports.Prepared) then qryReports.Prepare;

   qry.Open;
end;



procedure TfrmDesenhoRelCartaReajuste.FormClose(Sender: TObject; var Action: TCloseAction);
begin
   if qry.Active then qry.Close;
   if qryReports.Active then qryReports.Close;

   if qry.Prepared then qry.unPrepare;
   if qryReports.Prepared then qryReports.unPrepare;

   inherited;
end;



procedure TfrmDesenhoRelCartaReajuste.mnifilePageSetupClick(Sender: TObject);
var
   lPageSetupDlg: TppCustomPageSetupDialog;
   lFormClass: TFormClass;
begin
   inherited;

   if (DsgnCM.CurrentReport = nil) then Exit;

   lFormClass     := ppGetFormClass(TppCustomPageSetupDialog);
   lPageSetupDlg  := TppCustomPageSetupDialog(lFormClass.Create(Self));

   lPageSetupDlg.Report := DsgnCM.CurrentReport;
   lPageSetupDlg.ShowModal;

   lPageSetupDlg.Free;
end;



procedure TfrmDesenhoRelCartaReajuste.mnifilePrintClick(Sender: TObject);
begin
   inherited;

   if (DsgnCM.Report = nil) then Exit;
   DsgnCM.PrintReport;
end;



procedure TfrmDesenhoRelCartaReajuste.mnifilePrintToFileSetupClick(Sender: TObject);
var
   lTextFileDialog   : TppCustomPrintToFileSetupDialog;
   lFormClass        : TFormClass;
begin
   inherited;
   if (DsgnCM.CurrentReport = nil) then Exit;

   lFormClass        := ppGetFormClass(TppCustomPrintToFileSetupDialog);
   lTextFileDialog   := TppCustomPrintToFileSetupDialog(lFormClass.Create(Self));

   lTextFileDialog.Report        := DsgnCM.Report;
   lTextFileDialog.CurrentReport := DsgnCM.CurrentReport;

   lTextFileDialog.ShowModal;

   lTextFileDialog.Free;
end;



end.
