{*******************************************************}
{                                                       }
{   Padrão de Desenvolvimento - CM Soluções             }
{                                                       }
{   Copyright © 2000  CM Soluções Informática Ltda      }
{                                                       }
{*******************************************************}

   {$DEFINE CM3}
   {$IFNDEF VER100}
      {$DEFINE CM4}
      {$IFNDEF VER120}
         {$DEFINE CM5}
      {$ENDIF}
   {$ENDIF}
