CREATE OR REPLACE FUNCTION FN_EMP_OPERACAO(IDOPERACAO_P INT) RETURN INTEGER IS
  RESULT INTEGER;
BEGIN
  
   RESULT := (CASE WHEN IDOPERACAO_P = 0 THEN 1
          WHEN IDOPERACAO_P = 2 THEN 5             
          WHEN IDOPERACAO_P = 3 THEN 2
          END );
  
  RETURN(RESULT);
  
END FN_EMP_OPERACAO;
/
