CREATE TABLE CM.CONTRATOEMPTMOMSG (
	IDCONTRATOEMPTMO NUMBER,
	IDSEQUENCIA NUMBER NOT NULL,
	IDMODULO NUMBER,
	DESCRICAO VARCHAR(2000),
	TRGDTINCLUSAO DATE DEFAULT sysdate,
	TRGUSERINCLUSAO VARCHAR(30) DEFAULT user,
	DATAEXPIRAMSG DATE,
	FLGEXIBEMSG NUMBER(1)
);


-- CRIAÇÃO DA CHAVE PRIMARIA DA TABELA 
alter table CM.CONTRATOEMPTMOMSG
  add constraint XPKCONTRATOEMPTMOMSG primary key (IDSEQUENCIA)
  using index 
  tablespace INDICES
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 3208K
    minextents 1
    maxextents unlimited
  );

-- CRIAÇÃO DA CHAVE ESTRANGEIRA DA TABELA 
ALTER TABLE CM.CONTRATOEMPTMOMSG ADD CONSTRAINT FK_CONTRATOEMPTMOMSG
  FOREIGN KEY (IDCONTRATOEMPTMO) REFERENCES CM.CONTRATOEMPTMO (IDCONTRATOEMPTMO);


