<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ContabPOC.API\ContabPOC.API.csproj" />
    <ProjectReference Include="..\..\src\ContabPOC.Application\ContabPOC.Application.csproj" />
    <ProjectReference Include="..\..\src\ContabPOC.Domain\ContabPOC.Domain.csproj" />
    <ProjectReference Include="..\..\src\ContabPOC.Infrastructure\ContabPOC.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

</Project>
