<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContabPOC.Domain\ContabPOC.Domain.csproj" />
    <ProjectReference Include="..\ContabPOC.Application\ContabPOC.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- FUNCEF packages usando feed local -->
    <PackageReference Include="FUNCEF.ORM" />
    <PackageReference Include="FUNCEF.Cofre" />
    <PackageReference Include="FUNCEF.NoSql" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Oracle.EntityFrameworkCore" />
  </ItemGroup>

</Project>
