CREATE TABLE TBLMESTRE ( IDTBLMESTRE NUMBER, DESCTBLMESTRE VARCHAR2(60), VLRLIMITE NUMBER );
ALTER TABLE TBLMESTRE ADD PRIMARY KEY ( IDTBLMESTRE ); 
CREATE TABLE TBLDETALHE ( IDTBLDETALHE NUMBER, IDTBLMESTRE NUMBER, DESCTBLDETALHE VARCHAR2(60), VLRDETALHE NUMBER );
ALTER TABLE TBLDETALHE ADD PRIMARY KEY ( IDTBLDETALHE );
ALTER TABLE TBLDETALHE ADD FOREIGN KEY IDTBLMESTRE REFERENCES TBLMESTRE;