//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNCEF.Planus.WebEmprestimo.Web.Paginas.Inadimplencia.Consultas
{


    public partial class PopupHistoricoCobranca
    {

        /// <summary>
        /// caixaTextoObservacaoCobranca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox caixaTextoObservacaoCobranca;

        /// <summary>
        /// hdnObservacao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnObservacao;

        /// <summary>
        /// gridPrestacoesCobranca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.Grid gridPrestacoesCobranca;

        /// <summary>
        /// botaoVoltar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FUNCEF.Planus.GlobalWeb.Web.IU.Controles.BotaoVoltar botaoVoltar;
    }
}
